<!--
*Author：AlbertZhao
 *Contact：15505240996
 *代码由框架生成,任何更改都可能导致被代码生成器覆盖
 *业务请在@/extension/dataquery/albert_rfid/Albert_RFID.js此处编写
 -->
<template>
    <view-grid ref="grid"
               :columns="columns"
               :detail="detail"
               :editFormFields="editFormFields"
               :editFormOptions="editFormOptions"
               :searchFormFields="searchFormFields"
               :searchFormOptions="searchFormOptions"
               :table="table"
               :extend="extend">
    </view-grid>
</template>
<script>
    import extend from "@/extension/dataquery/albert_rfid/Albert_RFID.js";
    import { ref, defineComponent } from "vue";
    export default defineComponent({
        setup() {
            const table = ref({
                key: 'RFIDPkInt',
                footer: "Foots",
                cnName: 'RFID查询',
                name: 'albert_rfid/Albert_RFID',
                url: "/Albert_RFID/",
                sortName: "RFIDPkInt"
            });
            const editFormFields = ref({});
            const editFormOptions = ref([]);
            const searchFormFields = ref({"RFID":"","RFIDIsUse":"","SteelBall":"","PlugCap":"","Nut":"","Spring":"","Bearing":"","Case":""});
            const searchFormOptions = ref([[{"title":"RFID编号","field":"RFID","type":"text"},{"title":"RFID被占用","field":"RFIDIsUse","type":"text"},{"dataKey":"DeviceIsUse","data":[],"title":"钢球在位(Y/N)","field":"SteelBall"},{"dataKey":"DeviceIsUse","data":[],"title":"堵帽在位(Y/N)","field":"PlugCap"}],[{"dataKey":"DeviceIsUse","data":[],"title":"螺帽在位(Y/N)","field":"Nut"},{"dataKey":"DeviceIsUse","data":[],"title":"弹簧在位(Y/N)","field":"Spring"},{"dataKey":"DeviceIsUse","data":[],"title":"轴承在位(Y/N)","field":"Bearing"},{"dataKey":"DeviceIsUse","data":[],"title":"壳体在位(Y/N)","field":"Case"}]]);
            const columns = ref([{field:'RFIDPkInt',title:'RFID主键',type:'int',width:110,hidden:true,readonly:true,require:true,align:'left'},
                       {field:'RFID',title:'RFID编号',type:'string',width:120,readonly:true,align:'left',sort:true},
                       {field:'RFIDIsUse',title:'RFID被占用',type:'int',width:120,align:'left'},
                       {field:'ProductFunction',title:'工作类型（0正常件、1防错件、2返工件)',type:'string',width:120,align:'left'},
                       {field:'ProductContent',title:'工作内容',type:'string',width:120,align:'left'},
                       {field:'ProductCode',title:'产品码(轴承码）',type:'string',width:120,align:'left'},
                       {field:'ShellCode',title:'壳体码',type:'string',width:120,align:'left'},
                       {field:'RunCode',title:'执行器码',type:'string',width:120,align:'left'},
                       {field:'ErrorCode',title:'防错码',type:'string',width:120,align:'left'},
                       {field:'OpFinalResult',title:'最终结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op10Beat',title:'Op10节拍',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op10Result',title:'Op10结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op10Time',title:'Op10加工时间',type:'datetime',width:120,hidden:true,align:'left',sort:true},
                       {field:'SteelBall',title:'钢球在位(Y/N)',type:'string',bind:{ key:'DeviceIsUse',data:[]},width:110,hidden:true,align:'left'},
                       {field:'PlugCap',title:'堵帽在位(Y/N)',type:'string',bind:{ key:'DeviceIsUse',data:[]},width:110,hidden:true,align:'left'},
                       {field:'Nut',title:'螺帽在位(Y/N)',type:'string',bind:{ key:'DeviceIsUse',data:[]},width:110,hidden:true,align:'left'},
                       {field:'Spring',title:'弹簧在位(Y/N)',type:'string',bind:{ key:'DeviceIsUse',data:[]},width:110,hidden:true,align:'left'},
                       {field:'Bearing',title:'轴承在位(Y/N)',type:'string',bind:{ key:'DeviceIsUse',data:[]},width:110,hidden:true,align:'left'},
                       {field:'Case',title:'壳体在位(Y/N)',type:'string',bind:{ key:'DeviceIsUse',data:[]},width:110,hidden:true,align:'left'},
                       {field:'Op150Beat',title:'Op150节拍',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150Result',title:'Op150结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150Time',title:'Op150加工时间',type:'datetime',width:120,hidden:true,align:'left',sort:true},
                       {field:'Op160Beat',title:'Op160节拍',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op160Result',title:'Op160结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op160Time',title:'Op160加工时间',type:'datetime',width:120,hidden:true,align:'left',sort:true},
                       {field:'Op170Beat',title:'Op170节拍',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op170Result',title:'Op170结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op170Time',title:'Op170加工时间',type:'datetime',width:120,hidden:true,align:'left',sort:true},
                       {field:'Op170IV3Result',title:'Op170IV3结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op170IV3File',title:'Op170IV3照片',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_1Beat',title:'Op180_1节拍',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_1Result',title:'Op180_1结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_1Time',title:'Op180_1加工时间',type:'datetime',width:120,hidden:true,align:'left',sort:true},
                       {field:'Op180_2Beat',title:'Op180_2节拍',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_2Result',title:'Op180_2结果',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_2Time',title:'Op180_2加工时间',type:'datetime',width:120,hidden:true,align:'left',sort:true},
                       {field:'Op10WorkType',title:'预留',type:'string',width:120,hidden:true,align:'left'},
                       {field:'OpFinalStation',title:'最后执行站',type:'string',width:120,align:'left'},
                       {field:'Op10R_Get_Function',title:'OP10读取的Function',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op10R_Get_Content',title:'OP10读取的Content',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op10R_Send_Read',title:'OP10发送的读取信号',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op20R_Get_RFID',title:'OP20读取的RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op20R_Get_ProductCode',title:'OP20读取的轴承码',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op20R_Send_Read',title:'OP20发送的读取信号',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op30R_Get_RFID',title:'Op30R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op30R_Send_Read',title:'Op30R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op40R_Get_RFID',title:'Op40R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op40R_Send_Read',title:'Op40R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op50R_Get_RFID',title:'Op50R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op50R_Send_Read',title:'Op50R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op60R_Get_RFID',title:'Op60R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op60R_Send_Read',title:'Op60R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op70R_Get_RFID',title:'Op70R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op70R_Send_Read',title:'Op70R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op80R_Get_RFID',title:'Op80R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op80R_Get_ProductCode',title:'Op80R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op80R_Send_Read',title:'Op80R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op90R_Get_RFID',title:'Op90R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op90R_Send_Read',title:'Op90R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op100R_Get_RFID',title:'Op100R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op100R_Send_Read',title:'Op100R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op110R_Get_RFID',title:'Op110R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op110R_Send_Read',title:'Op110R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op120R_Get_RFID',title:'Op120R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op120R_Send_Read',title:'Op120R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op130R_Get_RFID',title:'Op130R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op130R_Send_Read',title:'Op130R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op135R_Get_RFID',title:'Op135R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op135R_Send_Read',title:'Op135R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op140R_Get_RFID',title:'Op140R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op140R_Send_Read',title:'Op140R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op10R_Get_RFID',title:'Op10R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150R_Get_RFID',title:'Op150R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150R_Get_Function',title:'Op150R_Get_Function',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150R_Get_Content',title:'Op150R_Get_Content',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150R_Get_ProductCode',title:'Op150R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op150R_Send_Read',title:'Op150R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op160R_Get_RFID',title:'Op160R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op160R_Send_Read',title:'Op160R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op170R_Get_RFID',title:'Op170R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op170R_Get_ProductCode',title:'Op170R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op170R_Send_Read',title:'Op170R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_1R_Get_RFID',title:'Op180_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_1R_Send_Read',title:'Op180_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_2R_Get_RFID',title:'Op180_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_2R_Send_Read',title:'Op180_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_3R_Get_RFID',title:'Op180_3R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_3R_Get_ProductCode',title:'Op180_3R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_3R_Get_ShellCode',title:'Op180_3R_Get_ShellCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op180_3R_Send_Read',title:'Op180_3R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op190R_Get_RFID',title:'Op190R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op190R_Send_Read',title:'Op190R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op200_1R_Get_RFID',title:'Op200_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op200_1R_Send_Read',title:'Op200_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op200_2R_Get_RFID',title:'Op200_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op200_2R_Send_Read',title:'Op200_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op210R_Get_RFID',title:'Op210R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op210R_Send_Read',title:'Op210R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op220R_Get_RFID',title:'Op220R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op220R_Send_Read',title:'Op220R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_1R_Get_RFID',title:'Op230_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_1R_Send_Read',title:'Op230_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_2R_Get_RFID',title:'Op230_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_2R_Send_Read',title:'Op230_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_3R_Get_RFID',title:'Op230_3R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_3R_Get_ProductCode',title:'Op230_3R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_3R_Send_Read',title:'Op230_3R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_4R_Get_RFID',title:'Op230_4R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_4R_Get_ProductCode',title:'Op230_4R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op230_4R_Send_Read',title:'Op230_4R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op240_1R_Get_RFID',title:'Op240_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op240_1R_Send_Read',title:'Op240_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op240_2R_Get_RFID',title:'Op240_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op240_2R_Get_ProductCode',title:'Op240_2R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op240_2R_Send_Read',title:'Op240_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op250_1R_Get_RFID',title:'Op250_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op250_1R_Send_Read',title:'Op250_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op250_2R_Get_RFID',title:'Op250_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op250_2R_Get_ProductCode',title:'Op250_2R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op250_2R_Send_Read',title:'Op250_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op260R_Get_RFID',title:'Op260R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op260R_Send_Read',title:'Op260R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op270R_Get_RFID',title:'Op270R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op270R_Send_Read',title:'Op270R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op280R_Get_RFID',title:'Op280R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op280R_Get_ProductCode',title:'Op280R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op280R_Send_Read',title:'Op280R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op290_1R_Get_RFID',title:'Op290_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op290_1R_Send_Read',title:'Op290_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op290_2R_Get_RFID',title:'Op290_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op290_2R_Get_ProductCode',title:'Op290_2R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op290_2R_Send_Read',title:'Op290_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op300_1R_Get_RFID',title:'Op300_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op300_1R_Send_Read',title:'Op300_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op300_2R_Get_RFID',title:'Op300_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op300_2R_Get_ProductCode',title:'Op300_2R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op300_2R_Send_Read',title:'Op300_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op310_1R_Get_RFID',title:'Op310_1R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op310_1R_Send_Read',title:'Op310_1R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op310_2R_Get_RFID',title:'Op310_2R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op310_2R_Get_ProductCode',title:'Op310_2R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op310_2R_Send_Read',title:'Op310_2R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op320R_Get_RFID',title:'Op320R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op320R_Get_ProductCode',title:'Op320R_Get_ProductCode',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op320R_Send_Read',title:'Op320R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op330R_Get_RFID',title:'Op330R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op330R_Send_Read',title:'Op330R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op340R_Get_RFID',title:'Op340R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op340R_Send_Read',title:'Op340R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op350R_Get_RFID',title:'Op350R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op350R_Send_Read',title:'Op350R_Send_Read',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op360R_Get_RFID',title:'Op360R_Get_RFID',type:'string',width:120,hidden:true,align:'left'},
                       {field:'Op360R_Send_Read',title:'Op360R_Send_Read',type:'string',width:120,hidden:true,align:'left'}]);
            const detail = ref({
                cnName: "#detailCnName",
                table: "#detailTable",
                columns: [],
                sortName: "",
                key: ""
            });
            return {
                table,
                extend,
                editFormFields,
                editFormOptions,
                searchFormFields,
                searchFormOptions,
                columns,
                detail,
            };
        },
    });
</script>
